class JargonLayer:
    def __init__(self):
        self.dictionary = {
            # --- GENERAL / CORE ---
            "función": "func",
            "funciones": "funcs",
            "parámetros": "params",
            "argumentos": "args",
            "configuración": "config",
            "información": "info",
            "identificador": "id",
            "variable": "var",
            "temporal": "tmp",
            "resultado": "res",
            "anterior": "prev",
            "siguiente": "next",
            "error": "err",
            "excepción": "exc",
            "instancia": "inst",
            "objeto": "obj",
            "clase": "cls",
            "iterador": "iter",
            "generador": "gen",
            "contexto": "ctx",
            "ayudante": "helper",
            "utilidad": "util",
            "biblioteca": "lib",
            "paquete": "pkg",
            "dependencia": "dep",
            "archivo": "file",
            "directorio": "dir",
            "camino": "path",

            # --- INFRA & DB ---
            "base de datos": "db",
            "conexión": "conn",
            "consulta": "query",
            "registro": "log",
            "servidor": "srv",
            "cliente": "cli",
            "producción": "prod",
            "desarrollo": "dev",
            "entorno": "env",
            "autenticación": "auth",
            "autorización": "authz",
            "petición": "req",
            "respuesta": "res",
            "cabecera": "hdr",
            "cuerpo": "body",
            "mensaje": "msg",

            # --- FRONTEND (React, JS, HTML/CSS) ---
            "componente": "comp",
            "propiedades": "props",
            "referencia": "ref",
            "estado": "state",
            "efecto": "effect",
            "gancho": "hook",
            "manejador": "handler",
            "evento": "evt",
            "navegación": "nav",
            "ventana": "win",
            "documento": "doc",
            "estilo": "style",
            "clase_css": "class",
            "botón": "btn",
            "formulario": "form",
            "entrada": "input",

            # --- BACKEND & PYTHON (Django/Flask) ---
            "modelo": "mdl",
            "vista": "view",
            "controlador": "ctrl",
            "serializador": "ser",
            "plantilla": "tpl",
            "decorador": "dec",
            "conjunto_datos": "ds",
            "entorno_virtual": "venv",
            "comando": "cmd",
            "tarea": "task",
            "cola": "queue",

            # --- LOW LEVEL & C ---
            "puntero": "ptr",
            "dirección": "addr",
            "memoria": "mem",
            "asignación": "alloc",
            "entero": "int",
            "cadena": "str",
            "carácter": "char",
            "arreglo": "arr",
            "matriz": "mtx",
            "búfer": "buf",
            "estructura": "struct",
            "fuente": "src",
            "destino": "dst",
            "valor": "val",
            "índice": "idx"
        }

    def apply(self, text):
        words = text.split()
        new_words = [self.dictionary.get(w, w) for w in words]
        return " ".join(new_words)